openapi: 3.0.1
info:
  title: sample
  version: 0.0.1
servers:
  - url: 'http://localhost:8080/api'
    description: Development server
  - url: 'https://localhost:8080/api'
    description: Development server with TLS Profile
paths:
  /countries:
    get:
      operationId: getAllCountries
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Country'
components:
  requestBodies:
    Country:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Country'
  schemas:
    Country:
      type: object
      required:
        - countryName
        - region
      properties:
        id:
          type: integer
          format: int64
        countryName:
          type: string
